### ISSUE TITLE
Floating point operation not support fpic

### ISSUE THREAD

**Issue by jackLanter** [usvi/F070RB-BL-FW#2]
Hello. I use your example on the stm32l051 chip. For floating point numbers, the linker supplies calls like __aeabi_fmul. There is an assumption that they are "broken" any such call breaks the execution of the program. Do you have any ideas about this?

**Comment by usvi** [comment]
Hello and thank you for interest towards my project.

(I'm a bit blind about floating point numbers because I don't use them in MCUs: They lose precision rapidly and yield somewhat unexpected results. Better thing to do would be to use fixed-point arithmetic if that was an option.)

Any idea if the floating point stuff comes from binary libraries? If they do, they have a lot of chance to cause problems. Including stuff from binary libraries probably needs PLT mechanism also.. which is a bit out of scope for this demonstration.

I found a couple of links I have glanced about PLT:
https://mcuoneclipse.com/2021/06/05/position-independent-code-with-gcc-for-arm-cortex-m/

https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table

(And also this more related to my thing in general: https://maskray.me/blog/2021-08-29-all-about-global-offset-table )

**Comment by jackLanter** [comment]
Many thanks for the work you have done. We decided to stop using floating point numbers in our project for slightly different reasons than those described by you. An analysis of the library function code showed that it accesses the r10 register, which probably breaks calls to got. The M0+ kernel also lacks separate division for integer types, but the library's inline subroutines (__udivsi3) do not cause such problems. Thank you again!

**Comment by usvi** [comment]
Your case is very interesting and valuable for other readers. In my point of view, all libraries like this are essentially black boxes which might have whatever optimizations yielding whatever register usage / overwrite. This is why I needed to recreate in inline assembly the one __libc_blah blah init function.

In general, I actually wish we could pass direct memory address to gcc for the r10, r9 or whatever register I have in use correctly for the GOT.

I hope you succeed in what you are working on.

Edit: Ok, thanks for closing. Good luck!
